# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#UTFSM_LABS WORK BLOCK_idS

b=Block.create(:name=>'3-4',:start_at=>'10:00',:end_at=>'11:30')
c=Block.create(:name=>'5-6',:start_at=>'11:45',:end_at=>'13:15')
d=Block.create(:name=>'7-8',:start_at=>'13:45',:end_at=>'15:15')
e=Block.create(:name=>'9-10',:start_at=>'15:25',:end_at=>'16:55')
f=Block.create(:name=>'11-12',:start_at=>'17:05',:end_at=>'18:35')
g=Block.create(:name=>'13-14',:start_at=>'18:45',:end_at=>'19:15')

s1b=Shift.create(:weekday=>'Lunes',:block_id=>b.id)
s2b=Shift.create(:weekday=>'Martes',:block_id=>b.id)
s3b=Shift.create(:weekday=>'Miércoles',:block_id=>b.id)
s4b=Shift.create(:weekday=>'Jueves',:block_id=>b.id)
s5b=Shift.create(:weekday=>'Viernes',:block_id=>b.id)
s1c=Shift.create(:weekday=>'Lunes',:block_id=>c.id)
s2c=Shift.create(:weekday=>'Martes',:block_id=>c.id)
s3c=Shift.create(:weekday=>'Miércoles',:block_id=>c.id)
s4c=Shift.create(:weekday=>'Jueves',:block_id=>c.id)
s5c=Shift.create(:weekday=>'Viernes',:block_id=>c.id)
s1d=Shift.create(:weekday=>'Lunes',:block_id=>d.id)
s2d=Shift.create(:weekday=>'Martes',:block_id=>d.id)
s3d=Shift.create(:weekday=>'Miércoles',:block_id=>d.id)
s4d=Shift.create(:weekday=>'Jueves',:block_id=>d.id, :meeting=>true)
s5d=Shift.create(:weekday=>'Viernes',:block_id=>d.id)
s1e=Shift.create(:weekday=>'Lunes',:block_id=>e.id)
s2e=Shift.create(:weekday=>'Martes',:block_id=>e.id)
s3e=Shift.create(:weekday=>'Miércoles',:block_id=>e.id)
s4e=Shift.create(:weekday=>'Jueves',:block_id=>e.id)
s5e=Shift.create(:weekday=>'Viernes',:block_id=>e.id)
s1f=Shift.create(:weekday=>'Lunes',:block_id=>f.id)
s2f=Shift.create(:weekday=>'Martes',:block_id=>f.id)
s3f=Shift.create(:weekday=>'Miércoles',:block_id=>f.id)
s4f=Shift.create(:weekday=>'Jueves',:block_id=>f.id)
s5f=Shift.create(:weekday=>'Viernes',:block_id=>f.id)
s1g=Shift.create(:weekday=>'Lunes',:block_id=>g.id)
s2g=Shift.create(:weekday=>'Martes',:block_id=>g.id)
s3g=Shift.create(:weekday=>'Miércoles',:block_id=>g.id)
s4g=Shift.create(:weekday=>'Jueves',:block_id=>g.id)
s5g=Shift.create(:weekday=>'Viernes',:block_id=>g.id)

p=Period.create(name: "2012-test", beginning: "2013-3-13", end_at: "2013-4-13")

ivan=Employee.create(:name=>"Iván")
fabian=Employee.create(:name=>"Fabian")
felipe=Employee.create(:name=>"Felipe")
tux=Employee.create(:name=>"Tux")
rene=Employee.create(:name=>"René")
nix=Employee.create(:name=>"Nix")
jorge=Employee.create(:name=>"Jorge")
denisse=Employee.create(:name=>"Denisse")
karu=Employee.create(:name=>"Karu")
nacho=Employee.create(:name=>"Nacho")
joaco=Employee.create(:name=>"Joaco")
lalz=Employee.create(:name=>"Lalz")
pollo=Employee.create(:name=>"Pollo")
igo=Employee.create(:name=>"Igo")
elian=Employee.create(:name=>"Elian")
maipu=Employee.create(:name=>"Maipú")

Checkin.create(:employee_id=>nix.id,:shift_id=>s1b.id,:period_id=>p.id)
Checkin.create(:employee_id=>denisse.id,:shift_id=>s2b.id,:period_id=>p.id)
Checkin.create(:employee_id=>pollo.id,:shift_id=>s3b.id,:period_id=>p.id)
Checkin.create(:employee_id=>elian.id,:shift_id=>s3b.id,:period_id=>p.id)
Checkin.create(:employee_id=>nix.id,:shift_id=>s4b.id,:period_id=>p.id)
Checkin.create(:employee_id=>lalz.id,:shift_id=>s5b.id,:period_id=>p.id)
Checkin.create(:employee_id=>nacho.id,:shift_id=>s5b.id,:period_id=>p.id)

Checkin.create(:employee_id=>igo.id,:shift_id=>s1c.id,:period_id=>p.id)
Checkin.create(:employee_id=>felipe.id,:shift_id=>s1c.id,:period_id=>p.id)
Checkin.create(:employee_id=>karu.id,:shift_id=>s2c.id,:period_id=>p.id)
Checkin.create(:employee_id=>nix.id,:shift_id=>s2c.id,:period_id=>p.id)
Checkin.create(:employee_id=>igo.id,:shift_id=>s3c.id,:period_id=>p.id)
Checkin.create(:employee_id=>fabian.id,:shift_id=>s4c.id,:period_id=>p.id)
Checkin.create(:employee_id=>felipe.id,:shift_id=>s4c.id,:period_id=>p.id)
Checkin.create(:employee_id=>fabian.id,:shift_id=>s5c.id,:period_id=>p.id)

Checkin.create(:employee_id=>pollo.id,:shift_id=>s1d.id,:period_id=>p.id)
Checkin.create(:employee_id=>nacho.id,:shift_id=>s1d.id,:period_id=>p.id)
Checkin.create(:employee_id=>nix.id,:shift_id=>s2d.id,:period_id=>p.id)
Checkin.create(:employee_id=>fabian.id,:shift_id=>s2d.id,:period_id=>p.id)
Checkin.create(:employee_id=>felipe.id,:shift_id=>s3d.id,:period_id=>p.id)

Employee.all.each do |emp|
	Checkin.create(:employee_id=>emp.id,:shift_id=>s4d.id,:period_id=>p.id)
end

Checkin.create(:employee_id=>karu.id,:shift_id=>s5d.id,:period_id=>p.id)
Checkin.create(:employee_id=>pollo.id,:shift_id=>s5d.id,:period_id=>p.id)

Checkin.create(:employee_id=>igo.id,:shift_id=>s1e.id,:period_id=>p.id)
Checkin.create(:employee_id=>nacho.id,:shift_id=>s2e.id,:period_id=>p.id)
Checkin.create(:employee_id=>igo.id,:shift_id=>s3e.id,:period_id=>p.id)
Checkin.create(:employee_id=>felipe.id,:shift_id=>s4e.id,:period_id=>p.id)
Checkin.create(:employee_id=>fabian.id,:shift_id=>s5e.id,:period_id=>p.id)

Checkin.create(:employee_id=>lalz.id,:shift_id=>s1f.id,:period_id=>p.id)
Checkin.create(:employee_id=>elian.id,:shift_id=>s1f.id,:period_id=>p.id)
Checkin.create(:employee_id=>joaco.id,:shift_id=>s2f.id,:period_id=>p.id)
Checkin.create(:employee_id=>denisse.id,:shift_id=>s3f.id,:period_id=>p.id)
Checkin.create(:employee_id=>pollo.id,:shift_id=>s3f.id,:period_id=>p.id)
Checkin.create(:employee_id=>elian.id,:shift_id=>s4f.id,:period_id=>p.id)
Checkin.create(:employee_id=>karu.id,:shift_id=>s5f.id,:period_id=>p.id)
Checkin.create(:employee_id=>joaco.id,:shift_id=>s5f.id,:period_id=>p.id)

Checkin.create(:employee_id=>lalz.id,:shift_id=>s1g.id,:period_id=>p.id)
Checkin.create(:employee_id=>nacho.id,:shift_id=>s2g.id,:period_id=>p.id)
Checkin.create(:employee_id=>joaco.id,:shift_id=>s2g.id,:period_id=>p.id)
Checkin.create(:employee_id=>lalz.id,:shift_id=>s3g.id,:period_id=>p.id)
Checkin.create(:employee_id=>denisse.id,:shift_id=>s3g.id,:period_id=>p.id)
Checkin.create(:employee_id=>elian.id,:shift_id=>s4g.id,:period_id=>p.id)
Checkin.create(:employee_id=>denisse.id,:shift_id=>s4g.id,:period_id=>p.id)
Checkin.create(:employee_id=>karu.id,:shift_id=>s5g.id,:period_id=>p.id)
Checkin.create(:employee_id=>joaco.id,:shift_id=>s5g.id,:period_id=>p.id)
